### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#1]
We need to create a logo that will represent the brand.

**Comment by jeet1703** [comment]
I would like to try to make the logo for this can you assign me the issue, please?

**Comment by prafull904434** [comment]
sir,
may i work with this issue ,can you assign to me

**Comment by thtauhid** [comment]
Hi @prafull904434 
Someone else is working on this issue at this moment. 

We'll be creating some new issues today. Join our discord server to get notified. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.
