### ISSUE TITLE
Extract github username from url if user inputs a github url and redirect properly

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#14]
Currently, 
On the homepage, we expect the user to input GitHub handle. But some users might paste GitHub URL. 

Here are the tasks that need to be done-
- [ ] If the user pastes a GitHub URL instead of GitHub username we need to extract the username from the url.
- [ ] Use the newly extracted username to navigate to user's profile page. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by irfanfaraaz** [comment]
@thtauhid Can i work on this?

**Comment by thtauhid** [comment]
@irfanfaraaz go ahead.


---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by irfanfaraaz** [comment]
@thtauhid is there anything you want me to improve?
