### ISSUE TITLE
Get social links from API

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#16]
Social links API is available now.

Call `getSociaLinks` function to get social links.

Need to integrate this in the Profile page. 
Currently, all the social links are showing. But, need to display only the links that are available through API. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by masterHAWK99** [comment]
I would like to work on this.

**Comment by thtauhid** [comment]
@masterHAWK99 go ahead.


---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.
