### ISSUE TITLE
Create react hook to update page title

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#2]

**Comment by CodeBreaker518** [comment]
I would like to contribute with this issue for the hackoberfest!, could you please assign it to me?

**Comment by CodeBreaker518** [comment]
Nevermind i didn't check that the project uses typescript:(

**Comment by kherin** [comment]
Hello @thtauhid, can you assign the issue to me?

**Comment by thtauhid** [comment]
@kherin go ahead.

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by prafull904434** [comment]
Hello ,sir may i work with this can you assign to me

**Comment by thtauhid** [comment]
Hi @prafull904434 
Thanks for your interest. 

Someone else is already working on this issue. 


---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by thtauhid** [comment]
Hello @kherin have you had a chance to dive into the issue yet? Need any help?

**Comment by kherin** [comment]
Hi @thtauhid , yes indeed I have already started working on it, I will push the first draft of the PR today itself

**Comment by kherin** [comment]
Hi @thtauhid , the related pull request #47 is now ready for review
