### ISSUE TITLE
Create Component for Projects

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#23]
Just need to follow the design pattern used in the [wireframe](https://github.com/thtauhid/open-profile/blob/main/Wireframe.pdf). This component should look like the `Top Repos` component. 

API available under `/src/api` name: getProjects

**Comment by Baburao-sanivada** [comment]
Can I Work On this Issue?

**Comment by thtauhid** [comment]
Hi @Baburao-sanivada go ahead


---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by Baburao-sanivada** [comment]
ThankYou

**Comment by viditagrawal56** [comment]
Hey @thtauhid was just wondering as the assignee has not made a pull request yet can I work on this issue?

**Comment by Baburao-sanivada** [comment]
No I will start to work on the issue Now

**Comment by thtauhid** [comment]
Hi @viditagrawal56 
All contributors get 2 days to start working. Contributors are unassigned from the issue if they have 0 activity for 2 days. 
Unfortunately, I can not assign you this issue. 

Hop on our discord server, I'll figure out something for you. 


---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by Baburao-sanivada** [comment]
Hello @thtauhid there isn't any design pattern for the Projects Component in the WireFrame and There isn't any Top Repos Component Also
Could You Help me With This?

**Comment by thtauhid** [comment]
This is the wireframe for `Top Repos`. Follow the same design for `Projects`
![image](https://github.com/thtauhid/open-profile/assets/13254850/35896104-318f-4fca-afc9-73aee68a63bf)

**Comment by Baburao-sanivada** [comment]
Does the Component need to occupy 1/2 the width of page  or full width. And For Each Project what is the Data Required(Is Title and Description Enough)

**Comment by thtauhid** [comment]
It'll occupy 1/2. 
Refer to this commit for data and API https://github.com/thtauhid/open-profile/commit/7deb7ecfcad90965e3fd3e378ab3a90010bd8832

**Comment by Baburao-sanivada** [comment]
got it
Will Start to Work on It Now

**Comment by thtauhid** [comment]
Few suggestions from my side-
1. Try to align the starting of the elements with the title
![image](https://github.com/thtauhid/open-profile/assets/13254850/2c6b3a31-0611-4335-b5a5-ef9f295b62e7)
2. The odd post should be on the left side rather than the center.

Everything else looks good.
