### ISSUE TITLE
Allow direct link access on vercel

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#26]
When we navigate through the UI there is no error. 
But, if we copy any link and directly access through it it throws 404. 

Need to add a vercel config file to handle this. 

Video:
https://github.com/thtauhid/open-profile/assets/13254850/2dcd74d9-c421-488f-8ad2-c270c809dbbb

Refer to https://stackoverflow.com/questions/64815012/why-does-react-router-not-works-at-vercel

**Comment by Shivampatil22** [comment]
Can you provide  a video or picture for more clarification and explain it in bit more detail

**Comment by Josephglz** [comment]
I could fix it
