### ISSUE TITLE
Create explore page

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#27]
Please follow the wireframe and create the explore page. 
You can use dummy data to create it. 

Link to wireframe: https://github.com/thtauhid/open-profile/blob/main/Wireframe.pdf

**Comment by Ryan-Maddock-96** [comment]
Hello, could I take this please? Just to confirm you want to create a new page "/explore" and just create a dummy file with users and render a tile for each?

**Comment by thtauhid** [comment]
Yes. Do refer to the wireframe for the design though. 
I've assigned this task to you. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by Ryan-Maddock-96** [comment]
Thank you!
