### ISSUE TITLE
Improve the UI of 404 page

### ISSUE THREAD

**Issue by Shivampatil22** [thtauhid/open-profile#32]
### **Current page**
![image](https://github.com/thtauhid/open-profile/assets/122476829/aee73682-03dc-4068-9b13-ae1cfb2c8542)

### **Suggested UI with a button to redirect to home page**

![image](https://github.com/thtauhid/open-profile/assets/122476829/a5a6e959-9d1c-4984-a1c2-aa0b7567f213)

**Comment by Shivampatil22** [comment]
Can you please assign this issue to me

**Comment by thtauhid** [comment]
Hi @Shivampatil22 
Can you explain what features you are going to add to the 404 Page UI?

**Comment by Shivampatil22** [comment]
### **1)Change the UI to above shown example .**
### **2)Button to redirect to Homepage.**

**Comment by thtauhid** [comment]
@Shivampatil22 go ahead. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by viditagrawal56** [comment]
Hey! I would like to work on this issue. Please assign it to me

**Comment by thtauhid** [comment]
Hi @viditagrawal56 
Someone is already working on this issue. 
Consider looking into other issues. 


---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by viditagrawal56** [comment]
Hey @thtauhid 
 I have the code ready let me know if needed!
