### ISSUE TITLE
Feature: GitHub API integration for user data

### ISSUE THREAD

**Issue by fiskryeziu** [thtauhid/open-profile#36]
### Description:
 Enable GitHub API integration to effortlessly access and display user data, enhancing the app's functionality and user experience.

**Comment by thtauhid** [comment]
Thank you @fiskryeziu 
This is definitely the direction we are heading to. 
Will be creating related issues & milestones soon. 

Regards 
THT


---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.
