### ISSUE TITLE
Create Blog Component for Recent Blogs of the User

### ISSUE THREAD

**Issue by Vijayabaskar56** [thtauhid/open-profile#37]
I can Create that, can you assign it to me.

**Comment by thtauhid** [comment]
Nice idea. 
Please share your plan. 

What data sources you think we should support?

**Comment by Vijayabaskar56** [comment]
Sources like hashnode which offers api, and we can fetch it and display it on ours.

**Comment by thtauhid** [comment]
Further discussion can be continued on #58
