### ISSUE TITLE
Create Component for `Bio / Intro` Section

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#4]
This section needs to be developed
![image](https://github.com/thtauhid/open-profile/assets/13254850/e33b5ed4-5082-40a9-99da-2687c0fb5433)

**Comment by shiv35** [comment]
please assign this issue to me

**Comment by thtauhid** [comment]
Hi @shiv35 
Thanks for your interest. 

This issue has already been solved. 
Feel free to check other available issues. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.
