### ISSUE TITLE
Enhancing User Data Retrieval with GitHub Personal Access Tokens.

### ISSUE THREAD

**Issue by satvik225** [thtauhid/open-profile#48]
Currently, we are using the static link to fetch users profile picture and username only. 
However, we can enhance our approach by implementing GitHub Personal Access Tokens. This way, we can access the user's data through a backend API, which can then be used to populate the relevant fields on the frontend, providing a more dynamic and secure solution.

**Comment by satvik225** [comment]
I can work on this issue once it's approved.

**Comment by thtauhid** [comment]
Hi @satvik225 
Using GitHub API to get dynamic data is something we are also planning.
We are currently in the process of creating the roadmap. 

We'll post on discord as soon as the roadmap is ready. 
Connect on discord to get notified. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by thtauhid** [comment]
Check #58
