### ISSUE TITLE
feat: Implementing last user searches functionality.

### ISSUE THREAD

**Issue by SAGARSINGH-1** [thtauhid/open-profile#50]
Implementing a GitHub username search feature on the page. This feature stores the last searched username in local storage and provides suggestions to the user based on their search history.

Suggestions in the below of input fields : 

![image](https://github.com/thtauhid/open-profile/assets/81561733/9717d738-224c-486d-a1fe-f0a5bfa62d99)

Ready to work in it.

**Comment by thtauhid** [comment]
Assigning to @SAGARSINGH-1 as he created the issue.

**Comment by SAGARSINGH-1** [comment]
hey @thtauhid is this good or we just redirect the user to that user Profile page : 

https://github.com/thtauhid/open-profile/assets/81561733/072c0e44-c2d7-4a7c-9583-2f67ca23143f

**Comment by thtauhid** [comment]
The search history needs to look a bit more elegant. 
When clicked, it should directly go to the user's profile.

**Comment by SAGARSINGH-1** [comment]
Hey @thtauhid check the referenced PR

**Comment by thtauhid** [comment]
Hi @SAGARSINGH-1 checked.
