### ISSUE TITLE
Unified design

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#52]
We need to make the design for each component similar. 

Currently, all the components have slightly different designs. 
All the designs need to look similar design-wise.
- All the heading should have the same color & same font size
- All borders need to be of the same color
- All fonts should have the same color 
- All spacing should be the same
![image](https://github.com/thtauhid/open-profile/assets/13254850/0cc85738-27ad-4f58-8eda-9ed71f6ff56c)
- Remove any background color. 

Though this is an EPIC issue but this issue will be assigned to one individual. 

Issues:
- [x] #53
- [x] #54
- [x] #55
- [x] #56
- [x] #57

**Comment by hritikadhikari05** [comment]
Hello @thtauhid I want to work on this issue.

**Comment by thtauhid** [comment]
@hritikadhikari05 assigned. 
Please create separate PRs for each issue. 

Thank you

**Comment by Vivek7038** [comment]
hey this is not fixed yet by one whom you assigned  kindly assign this to me , I can solve all issues in one day

**Comment by thtauhid** [comment]
> @thtauhid hey this is not fixed yet by one whom you assigned kindly assign this to me , I can solve all issues in one day

Please allow me some time to check. I'll take necessary step once I am done checking. 
Thanks
