### ISSUE TITLE
Bug: Empty searches are allowed

### ISSUE THREAD

**Issue by SAGARSINGH-1** [thtauhid/open-profile#68]
When a user press "enter" without a single character to input then it cause the empty box bug.

 

https://github.com/thtauhid/open-profile/assets/81561733/d2ccc35e-9c3d-47c5-a923-38f3f805f216

and yeah i am ready to work in this issue.

**Comment by half-real-SCRACX** [comment]
Wouldn't it be better if the app wouldn't let you make empty searches in the first place? That would be easy to implement.

**Comment by SAGARSINGH-1** [comment]
Yes it should be great idea.

**Comment by Parmesh119** [comment]
Hi @SAGARSINGH-1, I am Parmesh Bhatt.
I hope you are fine.
Can you please assign this issue to me?

**Comment by SAGARSINGH-1** [comment]
hey @Parmesh119 I didn't have the permission to do it.

**Comment by thtauhid** [comment]
Anyone willing to take up this issue please let me know. @SAGARSINGH-1 @half-real-SCRACX @Parmesh119

**Comment by half-real-SCRACX** [comment]
✋️

**Comment by SAGARSINGH-1** [comment]
Yes I can @thtauhid

**Comment by thtauhid** [comment]
@half-real-SCRACX if you already haven't started working, please skip working on this issue. @SAGARSINGH-1 has already created a PR.

**Comment by half-real-SCRACX** [comment]
Oh, ok, I'll work on the api one.
Today was a busy day, and I accepted the task at night
