### ISSUE TITLE
Create Component for `Working On` section

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#7]
This section needs to be developed
![image](https://github.com/thtauhid/open-profile/assets/13254850/fe9c42c6-2f67-4702-931e-6a51b7c5a58f)

**Comment by Shivampatil22** [comment]
Hi I would like to contribute to this issue under hacktoberfest ,so please assign me this issue

**Comment by thtauhid** [comment]
Hi @Shivampatil22 are you facing any difficulty?
Hop on our discord server and we can discuss. 


---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by Shivampatil22** [comment]
No I thought my PR's weren't accepted but after refreshing the browser they were accepted
and can you tell me how can I merge the base branch to with feature branch before making a pull request and resolve the conflicts.

**Comment by Shivampatil22** [comment]
Ok 
Thank u I will go through it
