### ISSUE TITLE
Create Component for `Testimonials` section

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/open-profile#8]
Need to develop this section

![image](https://github.com/thtauhid/open-profile/assets/13254850/677a7685-3525-4f6a-b214-dbe32864b8b5)

**Comment by Shivampatil22** [comment]
Hi I would like to work on this issue under hacktoberfest please assign me this issue.

**Comment by Shivampatil22** [comment]
### **Hi @thtauhid  are PR 's for hacktoberfest merged?**
### **Because in hacktoberfest account this PR's are not accepted**
### **Do you know what might be the reason?** 
![hack](https://github.com/thtauhid/open-profile/assets/122476829/17815717-0a55-4bd1-97c9-e917a5b18ca4)
